parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\UserProvider:
        arguments:
            $userRepository: '@App\Repository\UserRepository'
            $profileRepository: '@App\Repository\ProfileRepository'

    App\EventListener\IdGeneratorSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
