/** Zentrale SVG-Icons – immer über dieses Barrel importieren: `import { IconArrowRight } from '@/components/icons'` */
export { default as IconSvg } from './IconSvg.vue'

export { default as IconArrowRight } from './IconArrowRight.vue'
export { default as IconArrowLeft } from './IconArrowLeft.vue'
export { default as IconArrowUp } from './IconArrowUp.vue'
export { default as IconChevronRight } from './IconChevronRight.vue'
export { default as IconChevronDown } from './IconChevronDown.vue'
export { default as IconClose } from './IconClose.vue'
/** Alias — gleiches Icon wie IconClose; bevorzugt mdi-close */
export { default as IconCross } from './IconClose.vue'
export { default as IconPlus } from './IconPlus.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconPackage } from './IconPackage.vue'
export { default as IconTrash } from './IconTrash.vue'
export { default as IconEdit } from './IconEdit.vue'
export { default as IconEye } from './IconEye.vue'
export { default as IconAlertTriangle } from './IconAlertTriangle.vue'

export { default as IconDashboard } from './IconDashboard.vue'
export { default as IconActivities } from './IconActivities.vue'
export { default as IconMaterials } from './IconMaterials.vue'
export { default as IconContacts } from './IconContacts.vue'
/** Alias — gleiches SVG wie IconContacts; bevorzugt mdi-account-group */
export { default as IconEmployees } from './IconContacts.vue'
export { default as IconTasks } from './IconTasks.vue'
export { default as IconJobs } from './IconJobs.vue'
export { default as IconWorkshop } from './IconWorkshop.vue'
export { default as IconDisplay } from './IconDisplay.vue'
export { default as IconStatistics } from './IconStatistics.vue'
export { default as IconSettings } from './IconSettings.vue'
export { default as IconHelp } from './IconHelp.vue'
export { default as IconAccounting } from './IconAccounting.vue'
export { default as IconBell } from './IconBell.vue'
/** Alias — gleiches Icon wie IconChevronDown; bevorzugt mdi-chevron-down */
export { default as IconCollapse } from './IconChevronDown.vue'
